apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: practice
spec:
  selector:
    app: frontend-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
